#pragma once

/**
*	@brief Contains any enum related to rendering process.
*/
struct ShaderEnum
{
	/// [Shaders]

	enum ComputeShaderType : uint8_t
	{
		// Radix sort
		BIT_MASK_RADIX_SORT,
		DOWN_SWEEP_PREFIX_SCAN,
		END_LOOP_COMPUTATIONS,
		REALLOCATE_RADIX_SORT,
		REDUCE_PREFIX_SCAN,
		RESET_BUFFER_INDEX,
		RESET_LAST_POSITION_PREFIX_SCAN,

		// FRACTURER
		ASSIGN_FACE_CLUSTER,
		ASSIGN_VERTEX_CLUSTER,
		BUILD_MARCHING_CUBES_FACES,
		BUILD_REGULAR_GRID,
		COMPUTE_MORTON_CODES_FRACTURER,
		COUNT_QUADRANT_OCCUPANCY,
		COUNT_VOXEL_TRIANGLE,
		DETECT_BOUNDARIES,
		ERODE_GRID,
		FILL_REGULAR_GRID,
		FILL_REGULAR_GRID_VOXEL,
		FINISH_FILL,
		FINISH_LAPLACIAN_SMOOTHING,
		FLOOD_FRACTURER,
		FUSE_VERTICES_01,
		FUSE_VERTICES_02,
		LAPLACIAN_SMOOTHING,
		MARCHING_CUBES,
		MARK_BOUNDARY_TRIANGLES,
		NAIVE_FRACTURER,
		REMOVE_ISOLATED_REGIONS,
		RESET_BUFFER,
		RESET_LAPLACIAN_SMOOTHING,
		SAMPLER_SHADER,
		SELECT_VOXEL_TRIANGLE,
		UNDO_MASK_SHADER,

		NUM_COMPUTE_SHADERS
	};
};